import { StyleSheet } from "react-native";

export default StyleSheet.create({
  row: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    backgroundColor: "#fff",
  },
  heading: {
    color: "#000000",
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 19,
    padding: 10,
  },
  subheading: {
    color: "grey",
    fontSize: 15,
    letterSpacing: 0,
    paddingLeft: 10,
    paddingBottom: 5,
  },
  buttonGrey: {
    margin: 10,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "grey",
  },
  forwardButton: {
    margin: 10,
    height: 35,
    width: 90,
    justifyContent: "center",
  },
  cancelButton: {
    margin: 10,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#696969",
    height: 35,
    width: 90,
    justifyContent: "center",
  },
  pic: {
    borderRadius: 25,
    width: 50,
    height: 50,
  },
  nameContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 330,
  },
  nameTxt: {
    marginLeft: 15,
    fontWeight: "600",
    color: "#222",
    fontSize: 15,
  },
  time: {
    fontWeight: "200",
    color: "#777",
    fontSize: 13,
  },
  msgContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  msgTxt: {
    fontWeight: "400",
    color: "#666",
    fontSize: 12,
    marginLeft: 15,
    marginRight: 5,
  },
  circle: {
    width: 15,
    height: 15,
    borderRadius: 15 / 2,
    backgroundColor: "#88D969",
    borderWidth: 2,
    borderRightColor: "#fff",
    borderLeftColor: "#fff",
    borderTopColor: "#fff",
    borderBottomColor: "#fff",
    position: "absolute",
    top: -5,
    right: 0,
  },
});
